[versions]
agp = "9.0.1"
desugarJdkLibs = "2.1.5"
kotlin = "2.3.10"
ksp = "2.3.6"
hilt = "2.59.2"
kover = "0.9.7"
dependencyGuard = "0.5.0"
versionCatalogUpdate = "1.1.0"

kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.10.0"
kotlinxDatetime = "0.7.1"

androidxCore = "1.17.0"
androidxLifecycle = "2.10.0"
androidxActivity = "1.12.4"
androidxBrowser = "1.9.0"
androidxRoom = "2.8.4"
androidxComposeBom = "2026.02.01"
androidxNavigation3 = "1.0.1"
androidxHiltCompose = "1.3.0"
accompanist = "0.37.3"
material = "1.13.0"
ktor = "3.4.0"
okhttp = "5.3.2"

# test
junit = "4.13.2"
androidxJunit = "1.3.0"

ktlint = "1.8.0"

espressoCore = "3.7.0"
uiAutomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
baselineProfile = "1.5.0-alpha03"
profileInstaller = "1.4.1"
testRule = "1.7.0"

# for release

[libraries]
# classPath
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltAndroidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
kotlinxCoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinxSerializationCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxDatetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

androidxCore = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidxLifecycleRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidxLifecycleProcess = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidxLifecycleViewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidxBrowser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidxRoom = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidxRoomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }

androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidxHiltCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltCompose" }
androidxLifecycleViewModelNavigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidxLifecycle" }
androidxNavigation3Runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "androidxNavigation3" }
androidxNavigation3Ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "androidxNavigation3" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidxComposeUi = { group = "androidx.compose.ui", name = "ui" }
androidxComposeUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxComposeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxComposeMaterialIconsCore = { group = "androidx.compose.material", name = "material-icons-core" }
accompanistDrawablePainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

# test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }

espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
uiAutomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiAutomator" }
benchmarkMacroJunit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
profileInstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileInstaller" }
testRule = { group = "androidx.test", name = "rules", version.ref = "testRule" }

# debug
okhttpLoggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

# for release

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidxRoom = { id = "androidx.room", version.ref = "androidxRoom" }
hilt = { id = "dagger.hilt.android.plugin", version.ref = "hilt" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }

androidTest = { id = "com.android.test", version.ref = "agp" }
baselineProfile = { id = "androidx.baselineprofile", version.ref = "baselineProfile" }

# for release

[bundles]

# for release
